### ISSUE TITLE
default.sreg <-> class instances issue

### ISSUE THREAD

**Issue by jhalmen** [umit-iace/tool-pywisp#84]
first reported in #82, but the bug wasn't correctly identified there.
i reproduced and found the actual issue, opening this so it doesn't get forgotten, as i can't reopen #82 
the problem is, that the remote init code doesn't look at the defined modules and their `publicSettings`, it expects all these Settings to be redefined in the `default.sreg`.

so with my `testbench.py` defining:
``` python
class Leader(ExperimentModule):
    publicSettings = OrderedDict([("Manual", 0),
                                  ("Speed", 0),
                                  ("Rotation", 0)])
```
and my `default.sreg`:
```
- Name: Test

  Leader:

  Remote:
    Lead - Speed:
      Module: Leader
      Parameter: Speed
      maxSlider: '1'
      minSlider: '-1'
      shortcutMinus: Down
      shortcutPlus: Up
      stepSlider: '0.1'
      widgetType: Slider
```
this will crash, as `Leader` has `NoneType`, and the code is looking at `Leader['Speed']` to set the initial value.

if i just change the `default.sreg` to:
```
- Name: Test

  Leader:
    Manual: 1
    Speed: 0
    Rotation: 0

  Remote:
    Lead - Speed:
      Module: Leader
      Parameter: Speed
      maxSlider: '1'
      minSlider: '-1'
      shortcutMinus: Down
      shortcutPlus: Up
      stepSlider: '0.1'
      widgetType: Slider
```

this will finally work as intended.

@TanDro is this expected behaviour?
considering the defaults have to be defined in the class definitions anyway, and the `default.sreg` just offer the possibility of changing these defaults, i think it should be possible to use classes without having to redefine everything

_Originally posted by @jhalmen in https://github.com/umit-iace/tool-pywisp/issues/82#issuecomment-685591488_
